pipeline {
    agent {
        label 'server1'
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                echo "Building Python application..."
                mkdir -p artifacts
                zip -r artifacts/pythonapp.zip app.py README.md .gitignore
                '''
            }
        }

        stage('Test') {
            parallel {

                stage('Run Application') {
                    steps {
                        sh 'python3 app.py'
                    }
                }

                stage('Syntax Check') {
                    steps {
                        sh 'python3 -m py_compile app.py'
                    }
                }

            }
        }

        stage('Deploy') {
            steps {
                echo 'This is deploy stage'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'artifacts/*.zip'
            echo 'Artifact archived successfully'
        }
    }
}