pipeline {
    agent {
        label 'server1'
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                echo "Building Python application..."
                mkdir -p artifacts
                zip -r artifacts/pythonapp.zip app.py README.md .gitignore
                '''
            }

            post {
                success {
                    archiveArtifacts artifacts: 'artifacts/*.zip'
                }
            }
        }

        stage('Test') {
            steps {
                sh '''
                python3 app.py
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo 'This is deploy stage'
            }
        }
    }
}